### ISSUE TITLE
ImportError: No module named idawasm.loader

### ISSUE THREAD

**Issue by ghost** [fireeye/idawasm#4]
```
E:\IDA_Pro_v7.0_Portable\loaders\wasm_loader.py: No module named idawasm.loader
Traceback (most recent call last):
  File "E:\IDA_Pro_v7.0_Portable\python\ida_idaapi.py", line 553, in IDAPython_ExecScript
    execfile(script, g)
  File "E:/IDA_Pro_v7.0_Portable/loaders/wasm_loader.py", line 1, in <module>
    import idawasm.loader
ImportError: No module named idawasm.loader
E:\IDA_Pro_v7.0_Portable\loaders\wasm_loader.py: No module named idawasm.loader
Traceback (most recent call last):
  File "E:\IDA_Pro_v7.0_Portable\python\ida_idaapi.py", line 553, in IDAPython_ExecScript
    execfile(script, g)
  File "E:/IDA_Pro_v7.0_Portable/loaders/wasm_loader.py", line 1, in <module>
    import idawasm.loader
ImportError: No module named idawasm.loader
```

**Comment by ghost** [comment]
```
PROCESSOR_ENTRY: E:\IDA_Pro_v7.0_Portable\procs\wasm_proc.py: No module named idawasm.processor
Traceback (most recent call last):
  File "E:\IDA_Pro_v7.0_Portable\python\ida_idaapi.py", line 584, in IDAPython_LoadProcMod
    procmod = imp.load_module(procmod_name, fp, pathname, description)
  File "E:/IDA_Pro_v7.0_Portable/procs\wasm_proc.py", line 1, in <module>
    import idawasm.processor  # NOQA: F401 imported but unused
ImportError: No module named idawasm.processor
```

**Comment by williballenthin** [comment]
looks like the package is not installed correctly. did you follow the installation steps listed in the readme?

**Comment by ghost** [comment]
yes.I try to use python to run wasm_loader.py. when I import firist line(import idawasm.loader),it tell me No module named idaapi
Python 2.7.16 (v2.7.16:413a49145e, Mar  4 2019, 01:37:19) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import idawasm.loader
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build\bdist.win-amd64\egg\idawasm\loader.py", line 9, in <module>
ImportError: No module named idaapi
>>>

**Comment by ghost** [comment]
I move ida_idaapi.py to python libs but it doesn't work. I am no idea to deal with it

**Comment by williballenthin** [comment]
you need to install this package (`...python setup.py install`) using the python interpreter that IDA uses. you won't be able to load the module from a python prompt because things like `idaapi` are only available within IDA. you should be able to do `import idawasm` from within IDA if things are working correctly. I would verify that the path that IDA uses (`sys.path`) matches the installation of python that you've been using.

**Comment by ghost** [comment]
thanks.I had slove this. My ida has its own python. I add it to system path but not work.I use Absolute Path（D;\ida\python27\python.exe setup.py install）solve this

**Comment by godspeedcurry** [comment]
thank you, i solve the problem
